---
- name: "install-prometheus-server" 
  hosts: prometheus_server
  become: true 
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml

  roles:
    - install-prometheus-server
    - configure-prometheus-node-exporter