version: 2.1
orbs:
  slack: circleci/slack@4.9.3

jobs:
  build-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: Install Dependencies and Build Frontend
          command: |
            cd frontend
            echo "Install Dependencies"
            npm install
            echo "Build frontend"
            npm run build
            echo "frontend compiled files"
            ls dist
      - save_cache:
          paths:
            - frontend/node_modules
          key: frontend-build-{{ .Branch }}-{{ checksum "frontend/package-lock.json" }}
      - slack/notify:
          event: fail
          template: basic_fail_1
      - slack/notify:
          event: pass
          template: success_tagged_deploy_1

  test-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: 
           - frontend-build-{{ .Branch }}-{{ checksum "frontend/package-lock.json" }}
      - run:
          name: Test front-end
          command: |
            cd frontend
            npm test

  scan-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: 
           - frontend-build-{{ .Branch }}-{{ checksum "frontend/package-lock.json" }}
      - run:
          name: Front-end Scan with force fix
          command: |
            cd frontend
            ls node_modules
            npm audit fix --audit-level=critical --force
            npm audit --audit-level=critical

  build-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [backend-build]
      - run:
          name: Back-end build
          command: |
             cd backend
             npm install
             npm run build
             echo "backend compiled files"
             ls dist
      - save_cache:
          paths: 
            - backend/node_modules
          key: backend-build
      - slack/notify:
          event: fail
          template: basic_fail_1
      - slack/notify:
          event: pass
          template: success_tagged_deploy_1

  test-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [backend-build]
      - run:
          name: Back-end Test
          command: |
             cd backend
             npm test

  scan-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [backend-build]
      - run:
          name: Back-end Scan with force fix
          command: |
            cd backend
            npm audit fix --audit-level=critical --force
            npm audit --audit-level=critical


workflows:
  udapeople:
    jobs:
      - build-frontend:
          context: slack-secret
      - build-backend
      - test-frontend:
          requires: [build-frontend]
      - test-backend:
          requires: [build-backend]
      - scan-frontend:
          requires: [build-frontend]
      - scan-backend:
          requires: [build-backend]
