version: 2.1

jobs:
  build-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: 
           - frontend-build-{{ .Branch }}-{{ checksum "frontend/package-lock.json" }}
      - run:
          name: Install front-end Build dependencies
          command: |
            cd frontend
            npm install
      - run:
          name: Build front-end
          command: |
            pwd
            cd frontend
            npm run build
            echo "frontend compiled files"
            ls dist
      - save_cache:
          paths:
            - frontend/node_modules
            - frontend/package-lock.json
          key: frontend-build-{{ .Branch }}-{{ checksum "frontend/package-lock.json" }}

  build-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [backend-build]
      - run:
          name: Back-end build
          command: |
             cd backend
             npm install
             npm run build
             echo "backend compiled files"
             ls dist
      - save_cache:
          paths: [backend/node_modules,backend/package-lock.json]
          key: backend-build

  test-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: 
           - frontend-build-{{ .Branch }}-{{ checksum "frontend/package-lock.json" }}
      - run:
          name: Test front-end
          command: |
            cd frontend
            npm test
  test-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [backend-build]
      - run:
          name: Back-end Test
          command: |
             cd backend
             npm test

  scan-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: 
           - frontend-build-{{ .Branch }}-{{ checksum "frontend/package-lock.json" }}
      - run:
          name: Front-end Scan with force fix
          command: |
            cd frontend
            ls node_modules
            npm audit fix --audit-level=critical --force

  scan-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [backend-build]
      - run:
          name: Back-end Scan with force fix
          command: |
            cd backend
            npm audit fix --audit-level=critical --force

workflows:
  udapeople:
    jobs:
      - build-frontend
      - build-backend
      - test-frontend:
          requires: [build-frontend]
      - test-backend:
          requires: [build-backend]
      - scan-frontend:
          requires: [build-frontend]
      - scan-backend:
          requires: [build-backend]
